// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes(in *jlexer.Lexer, out *CliWalletResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "appID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AppID = string(in.String())
			}
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "rootPath":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RootPath = string(in.String())
			}
		case "alias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Alias = string(in.String())
			}
		case "algorithm":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Algorithm = string(in.String())
			}
		case "accountIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountIndex = int64(in.Int64())
			}
		case "createAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreateAt = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes(out *jwriter.Writer, in CliWalletResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"appID\":"
		out.RawString(prefix)
		out.String(string(in.AppID))
	}
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix)
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"rootPath\":"
		out.RawString(prefix)
		out.String(string(in.RootPath))
	}
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix)
		out.String(string(in.Alias))
	}
	if in.Algorithm != "" {
		const prefix string = ",\"algorithm\":"
		out.RawString(prefix)
		out.String(string(in.Algorithm))
	}
	{
		const prefix string = ",\"accountIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.AccountIndex))
	}
	{
		const prefix string = ",\"createAt\":"
		out.RawString(prefix)
		out.Int64(int64(in.CreateAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CliWalletResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CliWalletResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CliWalletResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CliWalletResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes(l, v)
}
func easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes1(in *jlexer.Lexer, out *CliSignTransactionRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "signerList":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.SignerList = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					(out.SignerList)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes1(out *jwriter.Writer, in CliSignTransactionRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"signerList\":"
		out.RawString(prefix[1:])
		if in.SignerList == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.SignerList {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v2Name))
				out.RawByte(':')
				out.String(string(v2Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CliSignTransactionRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CliSignTransactionRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CliSignTransactionRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CliSignTransactionRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes1(l, v)
}
func easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes2(in *jlexer.Lexer, out *CliSignTransactionReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = int64(in.Int64())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Data = string(in.String())
			}
		case "tradeSign":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TradeSign = string(in.String())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes2(out *jwriter.Writer, in CliSignTransactionReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Type))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		out.String(string(in.Data))
	}
	{
		const prefix string = ",\"tradeSign\":"
		out.RawString(prefix)
		out.String(string(in.TradeSign))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CliSignTransactionReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CliSignTransactionReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CliSignTransactionReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CliSignTransactionReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes2(l, v)
}
func easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes3(in *jlexer.Lexer, out *CliFindWalletListRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "result":
			if in.IsNull() {
				in.Skip()
				out.Result = nil
			} else {
				in.Delim('[')
				if out.Result == nil {
					if !in.IsDelim(']') {
						out.Result = make([]CliWalletResult, 0, 0)
					} else {
						out.Result = []CliWalletResult{}
					}
				} else {
					out.Result = (out.Result)[:0]
				}
				for !in.IsDelim(']') {
					var v3 CliWalletResult
					if in.IsNull() {
						in.Skip()
					} else {
						(v3).UnmarshalEasyJSON(in)
					}
					out.Result = append(out.Result, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes3(out *jwriter.Writer, in CliFindWalletListRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix[1:])
		if in.Result == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v4, v5 := range in.Result {
				if v4 > 0 {
					out.RawByte(',')
				}
				(v5).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CliFindWalletListRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CliFindWalletListRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CliFindWalletListRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CliFindWalletListRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes3(l, v)
}
func easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes4(in *jlexer.Lexer, out *CliFindWalletListReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes4(out *jwriter.Writer, in CliFindWalletListReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"cmd\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CliFindWalletListReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CliFindWalletListReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CliFindWalletListReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CliFindWalletListReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes4(l, v)
}
func easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes5(in *jlexer.Lexer, out *CliCreateMPCWalletRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "algorithm":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Algorithm = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes5(out *jwriter.Writer, in CliCreateMPCWalletRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix[1:])
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"algorithm\":"
		out.RawString(prefix)
		out.String(string(in.Algorithm))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CliCreateMPCWalletRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CliCreateMPCWalletRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CliCreateMPCWalletRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CliCreateMPCWalletRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes5(l, v)
}
func easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes6(in *jlexer.Lexer, out *CliCreateMPCWalletReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "alias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Alias = string(in.String())
			}
		case "algorithm":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Algorithm = string(in.String())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes6(out *jwriter.Writer, in CliCreateMPCWalletReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix[1:])
		out.String(string(in.Alias))
	}
	{
		const prefix string = ",\"algorithm\":"
		out.RawString(prefix)
		out.String(string(in.Algorithm))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CliCreateMPCWalletReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CliCreateMPCWalletReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CliCreateMPCWalletReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CliCreateMPCWalletReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes6(l, v)
}
func easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes7(in *jlexer.Lexer, out *CliCreateAddressRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "addressList":
			if in.IsNull() {
				in.Skip()
				out.AddressList = nil
			} else {
				in.Delim('[')
				if out.AddressList == nil {
					if !in.IsDelim(']') {
						out.AddressList = make([]CliAddressData, 0, 1)
					} else {
						out.AddressList = []CliAddressData{}
					}
				} else {
					out.AddressList = (out.AddressList)[:0]
				}
				for !in.IsDelim(']') {
					var v6 CliAddressData
					if in.IsNull() {
						in.Skip()
					} else {
						(v6).UnmarshalEasyJSON(in)
					}
					out.AddressList = append(out.AddressList, v6)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes7(out *jwriter.Writer, in CliCreateAddressRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"addressList\":"
		out.RawString(prefix[1:])
		if in.AddressList == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.AddressList {
				if v7 > 0 {
					out.RawByte(',')
				}
				(v8).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CliCreateAddressRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CliCreateAddressRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CliCreateAddressRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CliCreateAddressRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes7(l, v)
}
func easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes8(in *jlexer.Lexer, out *CliCreateAddressReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "accountIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountIndex = int64(in.Int64())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MainSymbol = string(in.String())
			}
		case "lastIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastIndex = int64(in.Int64())
			}
		case "count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Count = int64(in.Int64())
			}
		case "change":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Change = int64(in.Int64())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes8(out *jwriter.Writer, in CliCreateAddressReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix[1:])
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"accountIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.AccountIndex))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.MainSymbol))
	}
	{
		const prefix string = ",\"lastIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastIndex))
	}
	{
		const prefix string = ",\"count\":"
		out.RawString(prefix)
		out.Int64(int64(in.Count))
	}
	{
		const prefix string = ",\"change\":"
		out.RawString(prefix)
		out.Int64(int64(in.Change))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CliCreateAddressReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CliCreateAddressReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CliCreateAddressReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CliCreateAddressReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes8(l, v)
}
func easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes9(in *jlexer.Lexer, out *CliCreateAccountRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "otherOwnerKeys":
			if in.IsNull() {
				in.Skip()
				out.OtherOwnerKeys = nil
			} else {
				in.Delim('[')
				if out.OtherOwnerKeys == nil {
					if !in.IsDelim(']') {
						out.OtherOwnerKeys = make([]string, 0, 4)
					} else {
						out.OtherOwnerKeys = []string{}
					}
				} else {
					out.OtherOwnerKeys = (out.OtherOwnerKeys)[:0]
				}
				for !in.IsDelim(']') {
					var v9 string
					if in.IsNull() {
						in.Skip()
					} else {
						v9 = string(in.String())
					}
					out.OtherOwnerKeys = append(out.OtherOwnerKeys, v9)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "reqSigs":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReqSigs = int64(in.Int64())
			}
		case "publicKey":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PublicKey = string(in.String())
			}
		case "hdPath":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HdPath = string(in.String())
			}
		case "accountIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountIndex = int64(in.Int64())
			}
		case "addressIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AddressIndex = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes9(out *jwriter.Writer, in CliCreateAccountRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix[1:])
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"otherOwnerKeys\":"
		out.RawString(prefix)
		if in.OtherOwnerKeys == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v10, v11 := range in.OtherOwnerKeys {
				if v10 > 0 {
					out.RawByte(',')
				}
				out.String(string(v11))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"reqSigs\":"
		out.RawString(prefix)
		out.Int64(int64(in.ReqSigs))
	}
	{
		const prefix string = ",\"publicKey\":"
		out.RawString(prefix)
		out.String(string(in.PublicKey))
	}
	{
		const prefix string = ",\"hdPath\":"
		out.RawString(prefix)
		out.String(string(in.HdPath))
	}
	{
		const prefix string = ",\"accountIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.AccountIndex))
	}
	{
		const prefix string = ",\"addressIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.AddressIndex))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CliCreateAccountRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CliCreateAccountRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CliCreateAccountRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CliCreateAccountRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes9(l, v)
}
func easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes10(in *jlexer.Lexer, out *CliCreateAccountReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "lastIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastIndex = int64(in.Int64())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes10(out *jwriter.Writer, in CliCreateAccountReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix[1:])
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"lastIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastIndex))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CliCreateAccountReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CliCreateAccountReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CliCreateAccountReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CliCreateAccountReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes10(l, v)
}
func easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes11(in *jlexer.Lexer, out *CliAddressData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "addressIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AddressIndex = int64(in.Int64())
			}
		case "addressPubHex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AddressPubHex = string(in.String())
			}
		case "hdPath":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HdPath = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes11(out *jwriter.Writer, in CliAddressData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"addressIndex\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.AddressIndex))
	}
	{
		const prefix string = ",\"addressPubHex\":"
		out.RawString(prefix)
		out.String(string(in.AddressPubHex))
	}
	{
		const prefix string = ",\"hdPath\":"
		out.RawString(prefix)
		out.String(string(in.HdPath))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CliAddressData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CliAddressData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5d09f7cEncodeGithubComGodaddyXWalletApiGoTypes11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CliAddressData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CliAddressData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5d09f7cDecodeGithubComGodaddyXWalletApiGoTypes11(l, v)
}
