// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	json "encoding/json"
	types "github.com/godaddy-x/wallet-adapter/types"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson923d8b85DecodeGithubComGodaddyXWalletApiGoTypes(in *jlexer.Lexer, out *SubmitDeployContractRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "receipt":
			if in.IsNull() {
				in.Skip()
				out.Receipt = nil
			} else {
				if out.Receipt == nil {
					out.Receipt = new(types.SmartContractReceipt)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Receipt).UnmarshalEasyJSON(in)
				}
			}
		case "deployID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DeployID = int64(in.Int64())
			}
		case "templateID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TemplateID = int64(in.Int64())
			}
		case "contractAddress":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContractAddress = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = int64(in.Int64())
			}
		case "submitAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SubmitAt = int64(in.Int64())
			}
		case "confirmAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ConfirmAt = int64(in.Int64())
			}
		case "reason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Reason = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson923d8b85EncodeGithubComGodaddyXWalletApiGoTypes(out *jwriter.Writer, in SubmitDeployContractRes) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Receipt != nil {
		const prefix string = ",\"receipt\":"
		first = false
		out.RawString(prefix[1:])
		(*in.Receipt).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"deployID\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.DeployID))
	}
	{
		const prefix string = ",\"templateID\":"
		out.RawString(prefix)
		out.Int64(int64(in.TemplateID))
	}
	{
		const prefix string = ",\"contractAddress\":"
		out.RawString(prefix)
		out.String(string(in.ContractAddress))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.Int64(int64(in.Status))
	}
	{
		const prefix string = ",\"submitAt\":"
		out.RawString(prefix)
		out.Int64(int64(in.SubmitAt))
	}
	{
		const prefix string = ",\"confirmAt\":"
		out.RawString(prefix)
		out.Int64(int64(in.ConfirmAt))
	}
	{
		const prefix string = ",\"reason\":"
		out.RawString(prefix)
		out.String(string(in.Reason))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SubmitDeployContractRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson923d8b85EncodeGithubComGodaddyXWalletApiGoTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SubmitDeployContractRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson923d8b85EncodeGithubComGodaddyXWalletApiGoTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SubmitDeployContractRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson923d8b85DecodeGithubComGodaddyXWalletApiGoTypes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SubmitDeployContractRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson923d8b85DecodeGithubComGodaddyXWalletApiGoTypes(l, v)
}
func easyjson923d8b85DecodeGithubComGodaddyXWalletApiGoTypes1(in *jlexer.Lexer, out *SubmitDeployContractReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "templateID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TemplateID = int64(in.Int64())
			}
		case "pendingSignTx":
			if in.IsNull() {
				in.Skip()
				out.PendingSignTx = nil
			} else {
				if out.PendingSignTx == nil {
					out.PendingSignTx = new(types.PendingSignTx)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.PendingSignTx).UnmarshalEasyJSON(in)
				}
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson923d8b85EncodeGithubComGodaddyXWalletApiGoTypes1(out *jwriter.Writer, in SubmitDeployContractReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"templateID\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.TemplateID))
	}
	{
		const prefix string = ",\"pendingSignTx\":"
		out.RawString(prefix)
		if in.PendingSignTx == nil {
			out.RawString("null")
		} else {
			(*in.PendingSignTx).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SubmitDeployContractReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson923d8b85EncodeGithubComGodaddyXWalletApiGoTypes1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SubmitDeployContractReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson923d8b85EncodeGithubComGodaddyXWalletApiGoTypes1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SubmitDeployContractReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson923d8b85DecodeGithubComGodaddyXWalletApiGoTypes1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SubmitDeployContractReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson923d8b85DecodeGithubComGodaddyXWalletApiGoTypes1(l, v)
}
func easyjson923d8b85DecodeGithubComGodaddyXWalletApiGoTypes2(in *jlexer.Lexer, out *GetContractTemplatesRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "result":
			if in.IsNull() {
				in.Skip()
				out.Result = nil
			} else {
				in.Delim('[')
				if out.Result == nil {
					if !in.IsDelim(']') {
						out.Result = make([]ContractTemplateResult, 0, 0)
					} else {
						out.Result = []ContractTemplateResult{}
					}
				} else {
					out.Result = (out.Result)[:0]
				}
				for !in.IsDelim(']') {
					var v1 ContractTemplateResult
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Result = append(out.Result, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Limit).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson923d8b85EncodeGithubComGodaddyXWalletApiGoTypes2(out *jwriter.Writer, in GetContractTemplatesRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix[1:])
		if in.Result == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Result {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		(in.Limit).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetContractTemplatesRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson923d8b85EncodeGithubComGodaddyXWalletApiGoTypes2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetContractTemplatesRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson923d8b85EncodeGithubComGodaddyXWalletApiGoTypes2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetContractTemplatesRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson923d8b85DecodeGithubComGodaddyXWalletApiGoTypes2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetContractTemplatesRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson923d8b85DecodeGithubComGodaddyXWalletApiGoTypes2(l, v)
}
func easyjson923d8b85DecodeGithubComGodaddyXWalletApiGoTypes3(in *jlexer.Lexer, out *GetContractTemplatesReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "category":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Category = string(in.String())
			}
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "mainSymbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MainSymbol = string(in.String())
			}
		case "protocol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Protocol = string(in.String())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson923d8b85EncodeGithubComGodaddyXWalletApiGoTypes3(out *jwriter.Writer, in GetContractTemplatesReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix[1:])
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"mainSymbol\":"
		out.RawString(prefix)
		out.String(string(in.MainSymbol))
	}
	{
		const prefix string = ",\"protocol\":"
		out.RawString(prefix)
		out.String(string(in.Protocol))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetContractTemplatesReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson923d8b85EncodeGithubComGodaddyXWalletApiGoTypes3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetContractTemplatesReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson923d8b85EncodeGithubComGodaddyXWalletApiGoTypes3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetContractTemplatesReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson923d8b85DecodeGithubComGodaddyXWalletApiGoTypes3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetContractTemplatesReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson923d8b85DecodeGithubComGodaddyXWalletApiGoTypes3(l, v)
}
func easyjson923d8b85DecodeGithubComGodaddyXWalletApiGoTypes4(in *jlexer.Lexer, out *DeployContractRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "sid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sid = string(in.String())
			}
		case "pendingSignTx":
			if in.IsNull() {
				in.Skip()
				out.PendingSignTx = nil
			} else {
				in.Delim('[')
				if out.PendingSignTx == nil {
					if !in.IsDelim(']') {
						out.PendingSignTx = make([]*types.PendingSignTx, 0, 8)
					} else {
						out.PendingSignTx = []*types.PendingSignTx{}
					}
				} else {
					out.PendingSignTx = (out.PendingSignTx)[:0]
				}
				for !in.IsDelim(']') {
					var v4 *types.PendingSignTx
					if in.IsNull() {
						in.Skip()
						v4 = nil
					} else {
						if v4 == nil {
							v4 = new(types.PendingSignTx)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v4).UnmarshalEasyJSON(in)
						}
					}
					out.PendingSignTx = append(out.PendingSignTx, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson923d8b85EncodeGithubComGodaddyXWalletApiGoTypes4(out *jwriter.Writer, in DeployContractRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"sid\":"
		out.RawString(prefix[1:])
		out.String(string(in.Sid))
	}
	{
		const prefix string = ",\"pendingSignTx\":"
		out.RawString(prefix)
		if in.PendingSignTx == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.PendingSignTx {
				if v5 > 0 {
					out.RawByte(',')
				}
				if v6 == nil {
					out.RawString("null")
				} else {
					(*v6).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DeployContractRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson923d8b85EncodeGithubComGodaddyXWalletApiGoTypes4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DeployContractRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson923d8b85EncodeGithubComGodaddyXWalletApiGoTypes4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DeployContractRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson923d8b85DecodeGithubComGodaddyXWalletApiGoTypes4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DeployContractRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson923d8b85DecodeGithubComGodaddyXWalletApiGoTypes4(l, v)
}
func easyjson923d8b85DecodeGithubComGodaddyXWalletApiGoTypes5(in *jlexer.Lexer, out *DeployContractReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "templateID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TemplateID = int64(in.Int64())
			}
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "sid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sid = string(in.String())
			}
		case "txFrom":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxFrom = string(in.String())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "feeRate":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeeRate = string(in.String())
			}
		case "extParam":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExtParam = string(in.String())
			}
		case "memo":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Memo = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = string(in.String())
			}
		case "awaitResult":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AwaitResult = bool(in.Bool())
			}
		case "awaitTimeout":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AwaitTimeout = uint64(in.Uint64())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson923d8b85EncodeGithubComGodaddyXWalletApiGoTypes5(out *jwriter.Writer, in DeployContractReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"templateID\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.TemplateID))
	}
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"sid\":"
		out.RawString(prefix)
		out.String(string(in.Sid))
	}
	{
		const prefix string = ",\"txFrom\":"
		out.RawString(prefix)
		out.String(string(in.TxFrom))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"feeRate\":"
		out.RawString(prefix)
		out.String(string(in.FeeRate))
	}
	{
		const prefix string = ",\"extParam\":"
		out.RawString(prefix)
		out.String(string(in.ExtParam))
	}
	{
		const prefix string = ",\"memo\":"
		out.RawString(prefix)
		out.String(string(in.Memo))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.String(string(in.Value))
	}
	{
		const prefix string = ",\"awaitResult\":"
		out.RawString(prefix)
		out.Bool(bool(in.AwaitResult))
	}
	{
		const prefix string = ",\"awaitTimeout\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.AwaitTimeout))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DeployContractReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson923d8b85EncodeGithubComGodaddyXWalletApiGoTypes5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DeployContractReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson923d8b85EncodeGithubComGodaddyXWalletApiGoTypes5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DeployContractReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson923d8b85DecodeGithubComGodaddyXWalletApiGoTypes5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DeployContractReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson923d8b85DecodeGithubComGodaddyXWalletApiGoTypes5(l, v)
}
func easyjson923d8b85DecodeGithubComGodaddyXWalletApiGoTypes6(in *jlexer.Lexer, out *ContractTemplateResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "category":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Category = string(in.String())
			}
		case "mainSymbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MainSymbol = string(in.String())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "protocol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Protocol = string(in.String())
			}
		case "abi":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ABI = string(in.String())
			}
		case "bytecode":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Bytecode = string(in.String())
			}
		case "sourceCode":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SourceCode = string(in.String())
			}
		case "version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Version = string(in.String())
			}
		case "orderNo":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OrderNo = int64(in.Int64())
			}
		case "createAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreateAt = int64(in.Int64())
			}
		case "updateAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UpdateAt = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson923d8b85EncodeGithubComGodaddyXWalletApiGoTypes6(out *jwriter.Writer, in ContractTemplateResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"mainSymbol\":"
		out.RawString(prefix)
		out.String(string(in.MainSymbol))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"protocol\":"
		out.RawString(prefix)
		out.String(string(in.Protocol))
	}
	{
		const prefix string = ",\"abi\":"
		out.RawString(prefix)
		out.String(string(in.ABI))
	}
	{
		const prefix string = ",\"bytecode\":"
		out.RawString(prefix)
		out.String(string(in.Bytecode))
	}
	{
		const prefix string = ",\"sourceCode\":"
		out.RawString(prefix)
		out.String(string(in.SourceCode))
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.String(string(in.Version))
	}
	{
		const prefix string = ",\"orderNo\":"
		out.RawString(prefix)
		out.Int64(int64(in.OrderNo))
	}
	{
		const prefix string = ",\"createAt\":"
		out.RawString(prefix)
		out.Int64(int64(in.CreateAt))
	}
	{
		const prefix string = ",\"updateAt\":"
		out.RawString(prefix)
		out.Int64(int64(in.UpdateAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ContractTemplateResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson923d8b85EncodeGithubComGodaddyXWalletApiGoTypes6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ContractTemplateResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson923d8b85EncodeGithubComGodaddyXWalletApiGoTypes6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ContractTemplateResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson923d8b85DecodeGithubComGodaddyXWalletApiGoTypes6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ContractTemplateResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson923d8b85DecodeGithubComGodaddyXWalletApiGoTypes6(l, v)
}
