// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	json "encoding/json"
	types "github.com/godaddy-x/wallet-adapter/types"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson42340b0aDecodeGithubComGodaddyXWalletApiGoTypes(in *jlexer.Lexer, out *SubmitSmartContractTradeRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "receipt":
			if in.IsNull() {
				in.Skip()
				out.Receipt = nil
			} else {
				if out.Receipt == nil {
					out.Receipt = new(types.SmartContractReceipt)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Receipt).UnmarshalEasyJSON(in)
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson42340b0aEncodeGithubComGodaddyXWalletApiGoTypes(out *jwriter.Writer, in SubmitSmartContractTradeRes) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Receipt != nil {
		const prefix string = ",\"receipt\":"
		first = false
		out.RawString(prefix[1:])
		(*in.Receipt).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SubmitSmartContractTradeRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson42340b0aEncodeGithubComGodaddyXWalletApiGoTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SubmitSmartContractTradeRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson42340b0aEncodeGithubComGodaddyXWalletApiGoTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SubmitSmartContractTradeRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson42340b0aDecodeGithubComGodaddyXWalletApiGoTypes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SubmitSmartContractTradeRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson42340b0aDecodeGithubComGodaddyXWalletApiGoTypes(l, v)
}
func easyjson42340b0aDecodeGithubComGodaddyXWalletApiGoTypes1(in *jlexer.Lexer, out *SubmitSmartContractTradeReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "pendingSignTx":
			if in.IsNull() {
				in.Skip()
				out.PendingSignTx = nil
			} else {
				if out.PendingSignTx == nil {
					out.PendingSignTx = new(types.PendingSignTx)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.PendingSignTx).UnmarshalEasyJSON(in)
				}
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson42340b0aEncodeGithubComGodaddyXWalletApiGoTypes1(out *jwriter.Writer, in SubmitSmartContractTradeReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"pendingSignTx\":"
		out.RawString(prefix[1:])
		if in.PendingSignTx == nil {
			out.RawString("null")
		} else {
			(*in.PendingSignTx).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SubmitSmartContractTradeReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson42340b0aEncodeGithubComGodaddyXWalletApiGoTypes1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SubmitSmartContractTradeReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson42340b0aEncodeGithubComGodaddyXWalletApiGoTypes1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SubmitSmartContractTradeReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson42340b0aDecodeGithubComGodaddyXWalletApiGoTypes1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SubmitSmartContractTradeReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson42340b0aDecodeGithubComGodaddyXWalletApiGoTypes1(l, v)
}
func easyjson42340b0aDecodeGithubComGodaddyXWalletApiGoTypes2(in *jlexer.Lexer, out *GetContractsRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "result":
			if in.IsNull() {
				in.Skip()
				out.Result = nil
			} else {
				in.Delim('[')
				if out.Result == nil {
					if !in.IsDelim(']') {
						out.Result = make([]ContractResult, 0, 0)
					} else {
						out.Result = []ContractResult{}
					}
				} else {
					out.Result = (out.Result)[:0]
				}
				for !in.IsDelim(']') {
					var v1 ContractResult
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Result = append(out.Result, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Limit).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson42340b0aEncodeGithubComGodaddyXWalletApiGoTypes2(out *jwriter.Writer, in GetContractsRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix[1:])
		if in.Result == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Result {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		(in.Limit).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetContractsRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson42340b0aEncodeGithubComGodaddyXWalletApiGoTypes2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetContractsRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson42340b0aEncodeGithubComGodaddyXWalletApiGoTypes2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetContractsRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson42340b0aDecodeGithubComGodaddyXWalletApiGoTypes2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetContractsRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson42340b0aDecodeGithubComGodaddyXWalletApiGoTypes2(l, v)
}
func easyjson42340b0aDecodeGithubComGodaddyXWalletApiGoTypes3(in *jlexer.Lexer, out *GetContractsReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson42340b0aEncodeGithubComGodaddyXWalletApiGoTypes3(out *jwriter.Writer, in GetContractsReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"cmd\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetContractsReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson42340b0aEncodeGithubComGodaddyXWalletApiGoTypes3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetContractsReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson42340b0aEncodeGithubComGodaddyXWalletApiGoTypes3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetContractsReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson42340b0aDecodeGithubComGodaddyXWalletApiGoTypes3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetContractsReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson42340b0aDecodeGithubComGodaddyXWalletApiGoTypes3(l, v)
}
func easyjson42340b0aDecodeGithubComGodaddyXWalletApiGoTypes4(in *jlexer.Lexer, out *CreateSmartContractTradeReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "sid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sid = string(in.String())
			}
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Coin).UnmarshalEasyJSON(in)
			}
		case "feeRate":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeeRate = string(in.String())
			}
		case "extParam":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExtParam = string(in.String())
			}
		case "memo":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Memo = string(in.String())
			}
		case "to":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.To = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v4 string
					if in.IsNull() {
						in.Skip()
					} else {
						v4 = string(in.String())
					}
					(out.To)[key] = v4
					in.WantComma()
				}
				in.Delim('}')
			}
		case "raw":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Raw = string(in.String())
			}
		case "rawType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RawType = uint64(in.Uint64())
			}
		case "abiParam":
			if in.IsNull() {
				in.Skip()
				out.ABIParam = nil
			} else {
				in.Delim('[')
				if out.ABIParam == nil {
					if !in.IsDelim(']') {
						out.ABIParam = make([]string, 0, 4)
					} else {
						out.ABIParam = []string{}
					}
				} else {
					out.ABIParam = (out.ABIParam)[:0]
				}
				for !in.IsDelim(']') {
					var v5 string
					if in.IsNull() {
						in.Skip()
					} else {
						v5 = string(in.String())
					}
					out.ABIParam = append(out.ABIParam, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = string(in.String())
			}
		case "awaitResult":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AwaitResult = bool(in.Bool())
			}
		case "awaitTimeout":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AwaitTimeout = uint64(in.Uint64())
			}
		case "txFrom":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxFrom = string(in.String())
			}
		case "txTo":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxTo = string(in.String())
			}
		case "dataType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DataType = int64(in.Int64())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson42340b0aEncodeGithubComGodaddyXWalletApiGoTypes4(out *jwriter.Writer, in CreateSmartContractTradeReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix[1:])
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"sid\":"
		out.RawString(prefix)
		out.String(string(in.Sid))
	}
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix)
		(in.Coin).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"feeRate\":"
		out.RawString(prefix)
		out.String(string(in.FeeRate))
	}
	{
		const prefix string = ",\"extParam\":"
		out.RawString(prefix)
		out.String(string(in.ExtParam))
	}
	{
		const prefix string = ",\"memo\":"
		out.RawString(prefix)
		out.String(string(in.Memo))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		if in.To == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v6First := true
			for v6Name, v6Value := range in.To {
				if v6First {
					v6First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v6Name))
				out.RawByte(':')
				out.String(string(v6Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"raw\":"
		out.RawString(prefix)
		out.String(string(in.Raw))
	}
	{
		const prefix string = ",\"rawType\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.RawType))
	}
	{
		const prefix string = ",\"abiParam\":"
		out.RawString(prefix)
		if in.ABIParam == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.ABIParam {
				if v7 > 0 {
					out.RawByte(',')
				}
				out.String(string(v8))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.String(string(in.Value))
	}
	{
		const prefix string = ",\"awaitResult\":"
		out.RawString(prefix)
		out.Bool(bool(in.AwaitResult))
	}
	{
		const prefix string = ",\"awaitTimeout\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.AwaitTimeout))
	}
	{
		const prefix string = ",\"txFrom\":"
		out.RawString(prefix)
		out.String(string(in.TxFrom))
	}
	{
		const prefix string = ",\"txTo\":"
		out.RawString(prefix)
		out.String(string(in.TxTo))
	}
	{
		const prefix string = ",\"dataType\":"
		out.RawString(prefix)
		out.Int64(int64(in.DataType))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateSmartContractTradeReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson42340b0aEncodeGithubComGodaddyXWalletApiGoTypes4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateSmartContractTradeReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson42340b0aEncodeGithubComGodaddyXWalletApiGoTypes4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateSmartContractTradeReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson42340b0aDecodeGithubComGodaddyXWalletApiGoTypes4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateSmartContractTradeReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson42340b0aDecodeGithubComGodaddyXWalletApiGoTypes4(l, v)
}
func easyjson42340b0aDecodeGithubComGodaddyXWalletApiGoTypes5(in *jlexer.Lexer, out *ContractResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "icon":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Icon = string(in.String())
			}
		case "decimals":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Decimals = int64(in.Int64())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "token":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Token = string(in.String())
			}
		case "protocol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Protocol = string(in.String())
			}
		case "createAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreateAt = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson42340b0aEncodeGithubComGodaddyXWalletApiGoTypes5(out *jwriter.Writer, in ContractResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"icon\":"
		out.RawString(prefix)
		out.String(string(in.Icon))
	}
	{
		const prefix string = ",\"decimals\":"
		out.RawString(prefix)
		out.Int64(int64(in.Decimals))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"token\":"
		out.RawString(prefix)
		out.String(string(in.Token))
	}
	{
		const prefix string = ",\"protocol\":"
		out.RawString(prefix)
		out.String(string(in.Protocol))
	}
	{
		const prefix string = ",\"createAt\":"
		out.RawString(prefix)
		out.Int64(int64(in.CreateAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ContractResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson42340b0aEncodeGithubComGodaddyXWalletApiGoTypes5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ContractResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson42340b0aEncodeGithubComGodaddyXWalletApiGoTypes5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ContractResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson42340b0aDecodeGithubComGodaddyXWalletApiGoTypes5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ContractResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson42340b0aDecodeGithubComGodaddyXWalletApiGoTypes5(l, v)
}
func easyjson42340b0aDecodeGithubComGodaddyXWalletApiGoTypes6(in *jlexer.Lexer, out *CallSmartContractABIRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "method":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Method = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = string(in.String())
			}
		case "rawHex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RawHex = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = uint64(in.Uint64())
			}
		case "exception":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Exception = string(in.String())
			}
		case "uint256Wei":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Uint256Wei = string(in.String())
			}
		case "uint256Human":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Uint256Human = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson42340b0aEncodeGithubComGodaddyXWalletApiGoTypes6(out *jwriter.Writer, in CallSmartContractABIRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"method\":"
		out.RawString(prefix[1:])
		out.String(string(in.Method))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.String(string(in.Value))
	}
	{
		const prefix string = ",\"rawHex\":"
		out.RawString(prefix)
		out.String(string(in.RawHex))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Status))
	}
	{
		const prefix string = ",\"exception\":"
		out.RawString(prefix)
		out.String(string(in.Exception))
	}
	if in.Uint256Wei != "" {
		const prefix string = ",\"uint256Wei\":"
		out.RawString(prefix)
		out.String(string(in.Uint256Wei))
	}
	if in.Uint256Human != "" {
		const prefix string = ",\"uint256Human\":"
		out.RawString(prefix)
		out.String(string(in.Uint256Human))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CallSmartContractABIRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson42340b0aEncodeGithubComGodaddyXWalletApiGoTypes6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CallSmartContractABIRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson42340b0aEncodeGithubComGodaddyXWalletApiGoTypes6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CallSmartContractABIRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson42340b0aDecodeGithubComGodaddyXWalletApiGoTypes6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CallSmartContractABIRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson42340b0aDecodeGithubComGodaddyXWalletApiGoTypes6(l, v)
}
func easyjson42340b0aDecodeGithubComGodaddyXWalletApiGoTypes7(in *jlexer.Lexer, out *CallSmartContractABIReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "contractAddress":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContractAddress = string(in.String())
			}
		case "abiParam":
			if in.IsNull() {
				in.Skip()
				out.ABIParam = nil
			} else {
				in.Delim('[')
				if out.ABIParam == nil {
					if !in.IsDelim(']') {
						out.ABIParam = make([]string, 0, 4)
					} else {
						out.ABIParam = []string{}
					}
				} else {
					out.ABIParam = (out.ABIParam)[:0]
				}
				for !in.IsDelim(']') {
					var v9 string
					if in.IsNull() {
						in.Skip()
					} else {
						v9 = string(in.String())
					}
					out.ABIParam = append(out.ABIParam, v9)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "raw":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Raw = string(in.String())
			}
		case "rawType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RawType = uint64(in.Uint64())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = string(in.String())
			}
		case "txFrom":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxFrom = string(in.String())
			}
		case "dataType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DataType = int64(in.Int64())
			}
		case "decimals":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Decimals = int64(in.Int64())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson42340b0aEncodeGithubComGodaddyXWalletApiGoTypes7(out *jwriter.Writer, in CallSmartContractABIReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix[1:])
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"contractAddress\":"
		out.RawString(prefix)
		out.String(string(in.ContractAddress))
	}
	{
		const prefix string = ",\"abiParam\":"
		out.RawString(prefix)
		if in.ABIParam == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v10, v11 := range in.ABIParam {
				if v10 > 0 {
					out.RawByte(',')
				}
				out.String(string(v11))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"raw\":"
		out.RawString(prefix)
		out.String(string(in.Raw))
	}
	{
		const prefix string = ",\"rawType\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.RawType))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.String(string(in.Value))
	}
	{
		const prefix string = ",\"txFrom\":"
		out.RawString(prefix)
		out.String(string(in.TxFrom))
	}
	{
		const prefix string = ",\"dataType\":"
		out.RawString(prefix)
		out.Int64(int64(in.DataType))
	}
	{
		const prefix string = ",\"decimals\":"
		out.RawString(prefix)
		out.Int64(int64(in.Decimals))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CallSmartContractABIReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson42340b0aEncodeGithubComGodaddyXWalletApiGoTypes7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CallSmartContractABIReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson42340b0aEncodeGithubComGodaddyXWalletApiGoTypes7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CallSmartContractABIReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson42340b0aDecodeGithubComGodaddyXWalletApiGoTypes7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CallSmartContractABIReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson42340b0aDecodeGithubComGodaddyXWalletApiGoTypes7(l, v)
}
