// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson671f57afDecodeGithubComGodaddyXWalletApiGoTypes(in *jlexer.Lexer, out *MonitorAlertResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "appID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AppID = string(in.String())
			}
		case "domain":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Domain = string(in.String())
			}
		case "ruleID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RuleID = int64(in.Int64())
			}
		case "ruleCode":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RuleCode = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "category":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Category = string(in.String())
			}
		case "metric":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Metric = string(in.String())
			}
		case "level":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Level = int64(in.Int64())
			}
		case "windowType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WindowType = string(in.String())
			}
		case "bucketType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BucketType = string(in.String())
			}
		case "bucketStart":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BucketStart = int64(in.Int64())
			}
		case "scope":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Scope = string(in.String())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "contractAddress":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContractAddress = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "mainSymbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MainSymbol = string(in.String())
			}
		case "metricValue":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MetricValue = string(in.String())
			}
		case "thresholdValue":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ThresholdValue = string(in.String())
			}
		case "threshold2Value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Threshold2Value = string(in.String())
			}
		case "compareOp":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CompareOp = string(in.String())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		case "payload":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Payload = string(in.String())
			}
		case "alertLatency":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AlertLatency = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = int64(in.Int64())
			}
		case "createAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreateAt = int64(in.Int64())
			}
		case "updateAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UpdateAt = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson671f57afEncodeGithubComGodaddyXWalletApiGoTypes(out *jwriter.Writer, in MonitorAlertResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"appID\":"
		out.RawString(prefix)
		out.String(string(in.AppID))
	}
	{
		const prefix string = ",\"domain\":"
		out.RawString(prefix)
		out.String(string(in.Domain))
	}
	{
		const prefix string = ",\"ruleID\":"
		out.RawString(prefix)
		out.Int64(int64(in.RuleID))
	}
	{
		const prefix string = ",\"ruleCode\":"
		out.RawString(prefix)
		out.String(string(in.RuleCode))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"metric\":"
		out.RawString(prefix)
		out.String(string(in.Metric))
	}
	{
		const prefix string = ",\"level\":"
		out.RawString(prefix)
		out.Int64(int64(in.Level))
	}
	{
		const prefix string = ",\"windowType\":"
		out.RawString(prefix)
		out.String(string(in.WindowType))
	}
	{
		const prefix string = ",\"bucketType\":"
		out.RawString(prefix)
		out.String(string(in.BucketType))
	}
	{
		const prefix string = ",\"bucketStart\":"
		out.RawString(prefix)
		out.Int64(int64(in.BucketStart))
	}
	{
		const prefix string = ",\"scope\":"
		out.RawString(prefix)
		out.String(string(in.Scope))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"contractAddress\":"
		out.RawString(prefix)
		out.String(string(in.ContractAddress))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"mainSymbol\":"
		out.RawString(prefix)
		out.String(string(in.MainSymbol))
	}
	{
		const prefix string = ",\"metricValue\":"
		out.RawString(prefix)
		out.String(string(in.MetricValue))
	}
	{
		const prefix string = ",\"thresholdValue\":"
		out.RawString(prefix)
		out.String(string(in.ThresholdValue))
	}
	{
		const prefix string = ",\"threshold2Value\":"
		out.RawString(prefix)
		out.String(string(in.Threshold2Value))
	}
	{
		const prefix string = ",\"compareOp\":"
		out.RawString(prefix)
		out.String(string(in.CompareOp))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"payload\":"
		out.RawString(prefix)
		out.String(string(in.Payload))
	}
	{
		const prefix string = ",\"alertLatency\":"
		out.RawString(prefix)
		out.String(string(in.AlertLatency))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.Int64(int64(in.Status))
	}
	{
		const prefix string = ",\"createAt\":"
		out.RawString(prefix)
		out.Int64(int64(in.CreateAt))
	}
	{
		const prefix string = ",\"updateAt\":"
		out.RawString(prefix)
		out.Int64(int64(in.UpdateAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MonitorAlertResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson671f57afEncodeGithubComGodaddyXWalletApiGoTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MonitorAlertResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson671f57afEncodeGithubComGodaddyXWalletApiGoTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MonitorAlertResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson671f57afDecodeGithubComGodaddyXWalletApiGoTypes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MonitorAlertResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson671f57afDecodeGithubComGodaddyXWalletApiGoTypes(l, v)
}
func easyjson671f57afDecodeGithubComGodaddyXWalletApiGoTypes1(in *jlexer.Lexer, out *FindMonitorAlertRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "result":
			if in.IsNull() {
				in.Skip()
				out.Result = nil
			} else {
				in.Delim('[')
				if out.Result == nil {
					if !in.IsDelim(']') {
						out.Result = make([]MonitorAlertResult, 0, 0)
					} else {
						out.Result = []MonitorAlertResult{}
					}
				} else {
					out.Result = (out.Result)[:0]
				}
				for !in.IsDelim(']') {
					var v1 MonitorAlertResult
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Result = append(out.Result, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Limit).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson671f57afEncodeGithubComGodaddyXWalletApiGoTypes1(out *jwriter.Writer, in FindMonitorAlertRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix[1:])
		if in.Result == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Result {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		(in.Limit).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FindMonitorAlertRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson671f57afEncodeGithubComGodaddyXWalletApiGoTypes1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FindMonitorAlertRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson671f57afEncodeGithubComGodaddyXWalletApiGoTypes1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FindMonitorAlertRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson671f57afDecodeGithubComGodaddyXWalletApiGoTypes1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FindMonitorAlertRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson671f57afDecodeGithubComGodaddyXWalletApiGoTypes1(l, v)
}
func easyjson671f57afDecodeGithubComGodaddyXWalletApiGoTypes2(in *jlexer.Lexer, out *FindMonitorAlertReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson671f57afEncodeGithubComGodaddyXWalletApiGoTypes2(out *jwriter.Writer, in FindMonitorAlertReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"cmd\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FindMonitorAlertReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson671f57afEncodeGithubComGodaddyXWalletApiGoTypes2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FindMonitorAlertReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson671f57afEncodeGithubComGodaddyXWalletApiGoTypes2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FindMonitorAlertReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson671f57afDecodeGithubComGodaddyXWalletApiGoTypes2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FindMonitorAlertReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson671f57afDecodeGithubComGodaddyXWalletApiGoTypes2(l, v)
}
