// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonEfa995daDecodeGithubComGodaddyXWalletApiGoTypes(in *jlexer.Lexer, out *TradeNewlyResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "appID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AppID = string(in.String())
			}
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "sid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sid = string(in.String())
			}
		case "txID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxID = string(in.String())
			}
		case "txAction":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxAction = string(in.String())
			}
		case "flowType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FlowType = string(in.String())
			}
		case "fromAddress":
			if in.IsNull() {
				in.Skip()
				out.FromAddress = nil
			} else {
				in.Delim('[')
				if out.FromAddress == nil {
					if !in.IsDelim(']') {
						out.FromAddress = make([]string, 0, 4)
					} else {
						out.FromAddress = []string{}
					}
				} else {
					out.FromAddress = (out.FromAddress)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.FromAddress = append(out.FromAddress, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "fromAddressV":
			if in.IsNull() {
				in.Skip()
				out.FromAddressV = nil
			} else {
				in.Delim('[')
				if out.FromAddressV == nil {
					if !in.IsDelim(']') {
						out.FromAddressV = make([]string, 0, 4)
					} else {
						out.FromAddressV = []string{}
					}
				} else {
					out.FromAddressV = (out.FromAddressV)[:0]
				}
				for !in.IsDelim(']') {
					var v2 string
					if in.IsNull() {
						in.Skip()
					} else {
						v2 = string(in.String())
					}
					out.FromAddressV = append(out.FromAddressV, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "toAddress":
			if in.IsNull() {
				in.Skip()
				out.ToAddress = nil
			} else {
				in.Delim('[')
				if out.ToAddress == nil {
					if !in.IsDelim(']') {
						out.ToAddress = make([]string, 0, 4)
					} else {
						out.ToAddress = []string{}
					}
				} else {
					out.ToAddress = (out.ToAddress)[:0]
				}
				for !in.IsDelim(']') {
					var v3 string
					if in.IsNull() {
						in.Skip()
					} else {
						v3 = string(in.String())
					}
					out.ToAddress = append(out.ToAddress, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "toAddressV":
			if in.IsNull() {
				in.Skip()
				out.ToAddressV = nil
			} else {
				in.Delim('[')
				if out.ToAddressV == nil {
					if !in.IsDelim(']') {
						out.ToAddressV = make([]string, 0, 4)
					} else {
						out.ToAddressV = []string{}
					}
				} else {
					out.ToAddressV = (out.ToAddressV)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					if in.IsNull() {
						in.Skip()
					} else {
						v4 = string(in.String())
					}
					out.ToAddressV = append(out.ToAddressV, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Amount = string(in.String())
			}
		case "fees":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Fees = string(in.String())
			}
		case "mainSymbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MainSymbol = string(in.String())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "isContract":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsContract = bool(in.Bool())
			}
		case "blockHash":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHash = string(in.String())
			}
		case "blockHeight":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHeight = int64(in.Int64())
			}
		case "isMemo":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsMemo = bool(in.Bool())
			}
		case "memo":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Memo = string(in.String())
			}
		case "applyTime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ApplyTime = int64(in.Int64())
			}
		case "dataType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DataType = int64(in.Int64())
			}
		case "blockTime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockTime = int64(in.Int64())
			}
		case "decimals":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Decimals = int64(in.Int64())
			}
		case "contractToken":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContractToken = string(in.String())
			}
		case "contractAddress":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContractAddress = string(in.String())
			}
		case "success":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Success = string(in.String())
			}
		case "outputIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OutputIndex = int64(in.Int64())
			}
		case "signature":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Signature = string(in.String())
			}
		case "createAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreateAt = int64(in.Int64())
			}
		case "updateAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UpdateAt = int64(in.Int64())
			}
		case "uniqueHash":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UniqueHash = string(in.String())
			}
		case "needManualReview":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NeedManualReview = int64(in.Int64())
			}
		case "state":
			if in.IsNull() {
				in.Skip()
			} else {
				out.State = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEfa995daEncodeGithubComGodaddyXWalletApiGoTypes(out *jwriter.Writer, in TradeNewlyResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"appID\":"
		out.RawString(prefix)
		out.String(string(in.AppID))
	}
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix)
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"sid\":"
		out.RawString(prefix)
		out.String(string(in.Sid))
	}
	{
		const prefix string = ",\"txID\":"
		out.RawString(prefix)
		out.String(string(in.TxID))
	}
	{
		const prefix string = ",\"txAction\":"
		out.RawString(prefix)
		out.String(string(in.TxAction))
	}
	{
		const prefix string = ",\"flowType\":"
		out.RawString(prefix)
		out.String(string(in.FlowType))
	}
	{
		const prefix string = ",\"fromAddress\":"
		out.RawString(prefix)
		if in.FromAddress == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.FromAddress {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"fromAddressV\":"
		out.RawString(prefix)
		if in.FromAddressV == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.FromAddressV {
				if v7 > 0 {
					out.RawByte(',')
				}
				out.String(string(v8))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"toAddress\":"
		out.RawString(prefix)
		if in.ToAddress == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v9, v10 := range in.ToAddress {
				if v9 > 0 {
					out.RawByte(',')
				}
				out.String(string(v10))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"toAddressV\":"
		out.RawString(prefix)
		if in.ToAddressV == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.ToAddressV {
				if v11 > 0 {
					out.RawByte(',')
				}
				out.String(string(v12))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.String(string(in.Amount))
	}
	{
		const prefix string = ",\"fees\":"
		out.RawString(prefix)
		out.String(string(in.Fees))
	}
	{
		const prefix string = ",\"mainSymbol\":"
		out.RawString(prefix)
		out.String(string(in.MainSymbol))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"isContract\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsContract))
	}
	{
		const prefix string = ",\"blockHash\":"
		out.RawString(prefix)
		out.String(string(in.BlockHash))
	}
	{
		const prefix string = ",\"blockHeight\":"
		out.RawString(prefix)
		out.Int64(int64(in.BlockHeight))
	}
	{
		const prefix string = ",\"isMemo\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsMemo))
	}
	{
		const prefix string = ",\"memo\":"
		out.RawString(prefix)
		out.String(string(in.Memo))
	}
	{
		const prefix string = ",\"applyTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.ApplyTime))
	}
	{
		const prefix string = ",\"dataType\":"
		out.RawString(prefix)
		out.Int64(int64(in.DataType))
	}
	{
		const prefix string = ",\"blockTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.BlockTime))
	}
	{
		const prefix string = ",\"decimals\":"
		out.RawString(prefix)
		out.Int64(int64(in.Decimals))
	}
	{
		const prefix string = ",\"contractToken\":"
		out.RawString(prefix)
		out.String(string(in.ContractToken))
	}
	{
		const prefix string = ",\"contractAddress\":"
		out.RawString(prefix)
		out.String(string(in.ContractAddress))
	}
	{
		const prefix string = ",\"success\":"
		out.RawString(prefix)
		out.String(string(in.Success))
	}
	{
		const prefix string = ",\"outputIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.OutputIndex))
	}
	{
		const prefix string = ",\"signature\":"
		out.RawString(prefix)
		out.String(string(in.Signature))
	}
	{
		const prefix string = ",\"createAt\":"
		out.RawString(prefix)
		out.Int64(int64(in.CreateAt))
	}
	{
		const prefix string = ",\"updateAt\":"
		out.RawString(prefix)
		out.Int64(int64(in.UpdateAt))
	}
	{
		const prefix string = ",\"uniqueHash\":"
		out.RawString(prefix)
		out.String(string(in.UniqueHash))
	}
	{
		const prefix string = ",\"needManualReview\":"
		out.RawString(prefix)
		out.Int64(int64(in.NeedManualReview))
	}
	{
		const prefix string = ",\"state\":"
		out.RawString(prefix)
		out.Int64(int64(in.State))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TradeNewlyResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEfa995daEncodeGithubComGodaddyXWalletApiGoTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TradeNewlyResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEfa995daEncodeGithubComGodaddyXWalletApiGoTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TradeNewlyResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEfa995daDecodeGithubComGodaddyXWalletApiGoTypes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TradeNewlyResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEfa995daDecodeGithubComGodaddyXWalletApiGoTypes(l, v)
}
func easyjsonEfa995daDecodeGithubComGodaddyXWalletApiGoTypes1(in *jlexer.Lexer, out *FindTradeNewlyRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "result":
			if in.IsNull() {
				in.Skip()
				out.Result = nil
			} else {
				in.Delim('[')
				if out.Result == nil {
					if !in.IsDelim(']') {
						out.Result = make([]TradeNewlyResult, 0, 0)
					} else {
						out.Result = []TradeNewlyResult{}
					}
				} else {
					out.Result = (out.Result)[:0]
				}
				for !in.IsDelim(']') {
					var v13 TradeNewlyResult
					if in.IsNull() {
						in.Skip()
					} else {
						(v13).UnmarshalEasyJSON(in)
					}
					out.Result = append(out.Result, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Limit).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEfa995daEncodeGithubComGodaddyXWalletApiGoTypes1(out *jwriter.Writer, in FindTradeNewlyRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix[1:])
		if in.Result == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.Result {
				if v14 > 0 {
					out.RawByte(',')
				}
				(v15).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		(in.Limit).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FindTradeNewlyRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEfa995daEncodeGithubComGodaddyXWalletApiGoTypes1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FindTradeNewlyRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEfa995daEncodeGithubComGodaddyXWalletApiGoTypes1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FindTradeNewlyRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEfa995daDecodeGithubComGodaddyXWalletApiGoTypes1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FindTradeNewlyRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEfa995daDecodeGithubComGodaddyXWalletApiGoTypes1(l, v)
}
func easyjsonEfa995daDecodeGithubComGodaddyXWalletApiGoTypes2(in *jlexer.Lexer, out *FindTradeNewlyReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEfa995daEncodeGithubComGodaddyXWalletApiGoTypes2(out *jwriter.Writer, in FindTradeNewlyReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"cmd\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FindTradeNewlyReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEfa995daEncodeGithubComGodaddyXWalletApiGoTypes2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FindTradeNewlyReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEfa995daEncodeGithubComGodaddyXWalletApiGoTypes2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FindTradeNewlyReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEfa995daDecodeGithubComGodaddyXWalletApiGoTypes2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FindTradeNewlyReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEfa995daDecodeGithubComGodaddyXWalletApiGoTypes2(l, v)
}
